# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hhcZX5uaBIZahQahkLz1Jav3y3WTaund
"""

import matplotlib.image as img
import statistics
duck1 = img.imread('1.jpeg')
x=duck1.copy()
#print(x)
#print(x.shape)
#x.resize((193,261,3))#actual size
R,G,B,RGB,r,g,b=0,0,0,[],[],[],[]
#print(x[192][260][0])
for i in range(0,192):
  for j in range(0,260):
    R+=x[i][j][0]
    r.append(x[i][j][0])
RGB.append((R/(193*261)+0.5)//1)
for i in range(0,192):
  for j in range(0,260):
    G+=x[i][j][1]
    g.append(x[i][j][1])
RGB.append((G/(193*261)+0.5)//1)
for i in range(0,192):
  for j in range(0,260):
    B+=x[i][j][2]
    b.append(x[i][j][2])
RGB.append((B/(193*261)+0.5)//1)
print("The Mean Color value (RGB) in the given image is",RGB)
#y=[1,2,3]
RGB1=[statistics.mode(r),statistics.mode(g),statistics.mode(b)]
print("The Mode Color value (RGB) in the given image is",RGB1 )

"""https://drive.google.com/file/d/1GgeG0KAJdj6wQddI2J_BwfPa-DdutA_D/view?usp=sharing"""